version: '3.8'

services:
  mediafusion:
    image: mhdzumair/mediafusion:v3.8.1
    ports:
      - "8111:8111"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8111/health"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s

  nginx1:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mediafusion.local.pem:/etc/ssl/certs/mediafusion.local.pem
      - ./mediafusion.local-key.pem:/etc/ssl/private/mediafusion.local-key.pem
    ports:
      - "4433:4433"
    depends_on:
      - mediafusion

  mongodb1:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27117:27117"

  redis1:
    image: redis:latest
    ports:
      - "63179:63179"

  dramatiq-worker:
    image: mhdzumair/mediafusion:v3.8.1
    command: ["pipenv", "run", "dramatiq", "api.task", "-p", "2"]
    env_file:
      - .env
    depends_on:
      - mongodb1

  prowlarr4:
    image: ghcr.io/hotio/prowlarr:latest
    environment:
      PUID: "1000"
      PGID: "1000"
      UMASK: "002"
    ports:
      - "9494:9494"
    volumes:
      - prowlar-config:/config

volumes:
  mongo-data:
  prowlar-config:
